# Generated by Django 4.0 on 2022-01-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klmn',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
