# Generated by Django 4.0 on 2022-01-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='klmn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('costperitem', models.DecimalField(decimal_places=3, max_digits=20)),
                ('stockquantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
